= Caricamento dati e pipeline

== Obiettivo

In questa sezione descrivo e documento il processo operativo di caricamento e trasformazione dati su Snowflake, a partire da file *Parquet* nel Data Lake su Amazon S3.
Il processo è *uno solo*, verificabile end-to-end, ed è eseguito esclusivamente tramite *TASK chain* che invoca tre procedure SQL con `EXECUTE AS OWNER`:

*S3 → stage esterno → RAW (COPY INTO) → CURATED (quarantena + MERGE) → ANALYTICS (MERGE) → orchestrazione con task chain*.

== Ingestione e staging

L'ingestione avviene in modalità *pull* da S3 tramite *Storage Integration* e stage esterno, senza credenziali statiche e con *least privilege*.

*A) Bucket S3 e struttura prefix*

Il Data Lake risiede su Amazon S3 (regione `eu-central-1`) con bucket privato e *Block Public Access* attivo:

- Bucket: `healthcare-data-prod-eu`
- Base path: `s3://healthcare-data-prod-eu/snowflake/raw/`
- Prefix per domini:
  - `ehr/` (es. `ehr/pazienti/`, `ehr/ricoveri/`)
  - `erp/` (es. `erp/reparti/`)
  - `iot/` (es. `iot/dispositivi/`, `iot/parametri_vitali/`)

*B) IAM Role + policy (least privilege)*

L'accesso cross-account da Snowflake a S3 utilizza un ruolo IAM dedicato:

- Role: `snowflake_s3_readonly_role`
- Policy: `snowflake_s3_raw_read_policy` con soli privilegi `s3:ListBucket` e `s3:GetObject` sulle risorse:
  - `arn:aws:s3:::healthcare-data-prod-eu`
  - `arn:aws:s3:::healthcare-data-prod-eu/snowflake/raw/*`

*C) Storage Integration e trust policy (cross-account)*

La *Storage Integration* è un oggetto di account e viene creata con privilegi amministrativi.

#figure(
	```sql
USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE STORAGE INTEGRATION s3_int_healthcare_data
	TYPE = EXTERNAL_STAGE
	STORAGE_PROVIDER = S3
	ENABLED = TRUE
	STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::123456789012:role/snowflake_s3_readonly_role'
	STORAGE_ALLOWED_LOCATIONS = ('s3://healthcare-data-prod-eu/snowflake/raw/');
```,
	caption: "Creazione Storage Integration per accesso a S3"
)

I parametri necessari alla trust policy AWS vengono recuperati dall'integrazione:

#figure(
	```sql
DESC INTEGRATION s3_int_healthcare_data;
```,
	caption: "Recupero parametri per la trust policy (cross-account)"
)

Dal risultato si copiano i valori:

- `STORAGE_AWS_IAM_USER_ARN`
- `STORAGE_AWS_EXTERNAL_ID`

La trust policy del ruolo IAM utilizza questi due valori per prevenire *confused deputy*.

#figure(
	```json
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Sid": "AllowSnowflakeAssumeRole",
			"Effect": "Allow",
			"Principal": {
				"AWS": "<SNOWFLAKE_IAM_USER_ARN>"
			},
			"Action": "sts:AssumeRole",
			"Condition": {
				"StringEquals": {
					"sts:ExternalId": "<SNOWFLAKE_EXTERNAL_ID>"
				}
			}
		}
	]
}
```,
	caption: "Trust policy del ruolo IAM (valori Snowflake reali sostituiti con placeholder)"
)

*D) File format Parquet e stage esterno*

File format e stage esterno sono creati nello schema `RAW` del database `HEALTHCARE_DW`.

#figure(
	```sql
USE ROLE ACCOUNTADMIN;
USE DATABASE HEALTHCARE_DW;
USE SCHEMA HEALTHCARE_DW.RAW;

CREATE OR REPLACE FILE FORMAT ff_parquet
	TYPE = PARQUET;

CREATE OR REPLACE STAGE stage_healthcare_raw
	URL = 's3://healthcare-data-prod-eu/snowflake/raw/'
	STORAGE_INTEGRATION = s3_int_healthcare_data
	FILE_FORMAT = ff_parquet;
```,
	caption: "Creazione file format Parquet e stage esterno su S3"
)

*E) Verifica stage (evidenza di listing)*

Le evidenze operative sono `SHOW/DESC` e `LIST` sul prefix atteso.

```sql
SHOW STAGES LIKE 'STAGE_HEALTHCARE_RAW' IN SCHEMA HEALTHCARE_DW.RAW;
DESC STAGE HEALTHCARE_DW.RAW.stage_healthcare_raw;
```

```sql
LIST @HEALTHCARE_DW.RAW.stage_healthcare_raw/ehr/pazienti/;
```

== Pipeline ELT (flusso unico: task → procedure)

Il processo ELT è eseguito *solo* tramite task chain nello schema tecnico `HEALTHCARE_DW.PIPELINE`.
Le tre procedure sono idempotenti e vengono invocate in sequenza fissa:

1. `sp_load_raw()` → carica `RAW.*` con `COPY INTO` (fail-fast).
2. `sp_transform_curated()` → quarantena e popolamento `CURATED.*` esclusivamente via `MERGE`.
3. `sp_publish_analytics()` → popolamento `ANALYTICS.*` esclusivamente via `MERGE`.

=== 1) RAW: sp_load_raw() (COPY INTO, fail-fast)

La procedura di ingestione usa `WH_INGEST` e carica le tabelle mirror nel layer `RAW`.
Ogni `COPY INTO` opera con `ON_ERROR = 'ABORT_STATEMENT'` per interrompere in modo deterministico su incompatibilità schema/file.

```sql
USE ROLE ROLE_DATA_ENGINEER;
USE DATABASE HEALTHCARE_DW;
USE SCHEMA HEALTHCARE_DW.PIPELINE;

CREATE OR REPLACE PROCEDURE sp_load_raw()
	RETURNS STRING
	LANGUAGE SQL
	EXECUTE AS OWNER
AS
$$
BEGIN
	COPY INTO HEALTHCARE_DW.RAW.PAZIENTI
	FROM @HEALTHCARE_DW.RAW.stage_healthcare_raw/ehr/pazienti/
	FILE_FORMAT = (TYPE = PARQUET)
	MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
	ON_ERROR = 'ABORT_STATEMENT';

	COPY INTO HEALTHCARE_DW.RAW.REPARTI
	FROM @HEALTHCARE_DW.RAW.stage_healthcare_raw/erp/reparti/
	FILE_FORMAT = (TYPE = PARQUET)
	MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
	ON_ERROR = 'ABORT_STATEMENT';

	COPY INTO HEALTHCARE_DW.RAW.DISPOSITIVI
	FROM @HEALTHCARE_DW.RAW.stage_healthcare_raw/iot/dispositivi/
	FILE_FORMAT = (TYPE = PARQUET)
	MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
	ON_ERROR = 'ABORT_STATEMENT';

	COPY INTO HEALTHCARE_DW.RAW.RICOVERI
	FROM @HEALTHCARE_DW.RAW.stage_healthcare_raw/ehr/ricoveri/
	FILE_FORMAT = (TYPE = PARQUET)
	MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
	ON_ERROR = 'ABORT_STATEMENT';

	COPY INTO HEALTHCARE_DW.RAW.PARAMETRI_VITALI
	FROM @HEALTHCARE_DW.RAW.stage_healthcare_raw/iot/parametri_vitali/
	FILE_FORMAT = (TYPE = PARQUET)
	MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
	ON_ERROR = 'ABORT_STATEMENT';

	RETURN 'OK';
END;
$$;
```

=== 2) CURATED: sp_transform_curated() (quarantena + MERGE, idempotente)

Il layer `CURATED` viene popolato esclusivamente via `MERGE` sulle business key.
Le anomalie (chiavi nulle e/o riferimenti orfani) vengono isolate solo tramite `INSERT` nelle tabelle `*_QUARANTENA`.

```sql
USE ROLE ROLE_DATA_ENGINEER;
USE DATABASE HEALTHCARE_DW;
USE SCHEMA HEALTHCARE_DW.PIPELINE;

CREATE OR REPLACE PROCEDURE sp_transform_curated()
	RETURNS STRING
	LANGUAGE SQL
	EXECUTE AS OWNER
AS
$$
BEGIN
	-- a) Quarantena come snapshot per run
	TRUNCATE TABLE HEALTHCARE_DW.CURATED.RICOVERI_QUARANTENA;
	TRUNCATE TABLE HEALTHCARE_DW.CURATED.PARAMETRI_VITALI_QUARANTENA;

	-- b) MERGE CURATED.PAZIENTI (dedup deterministica su ID_PAZIENTE)
	MERGE INTO HEALTHCARE_DW.CURATED.PAZIENTI t
	USING (
		SELECT
			r.ID_PAZIENTE,
			r.CODICE_FISCALE,
			r.NOME,
			r.COGNOME,
			r.SESSO,
			r.DATA_NASCITA,
			r.STATO_CIVILE,
			r.LINGUA_PRIMARIA,
			r.GRUPPO_SANGUIGNO,
			r.CITTA,
			r.INDIRIZZO,
			r.CAP,
			r.PAESE,
			r.EMAIL,
			r.TELEFONO,
			r.COMPAGNIA_ASSICURATIVA,
			r.PIANO_ASSICURATIVO,
			r.ID_ASSICURAZIONE,
			r.CONTATTO_EMERGENZA_NOME,
			r.CONTATTO_EMERGENZA_TELEFONO,
			r.ALTEZZA_CM,
			r.PESO_KG
		FROM HEALTHCARE_DW.RAW.PAZIENTI r
		WHERE r.ID_PAZIENTE IS NOT NULL
		QUALIFY ROW_NUMBER() OVER (
			PARTITION BY r.ID_PAZIENTE
			ORDER BY MD5(
				TO_VARCHAR(
					OBJECT_CONSTRUCT_KEEP_NULL(
						'CODICE_FISCALE', r.CODICE_FISCALE,
						'NOME', r.NOME,
						'COGNOME', r.COGNOME,
						'SESSO', r.SESSO,
						'DATA_NASCITA', r.DATA_NASCITA,
						'GRUPPO_SANGUIGNO', r.GRUPPO_SANGUIGNO,
						'CITTA', r.CITTA,
						'INDIRIZZO', r.INDIRIZZO,
						'CAP', r.CAP,
						'PAESE', r.PAESE,
						'EMAIL', r.EMAIL,
						'TELEFONO', r.TELEFONO,
						'PIANO_ASSICURATIVO', r.PIANO_ASSICURATIVO,
						'ID_ASSICURAZIONE', r.ID_ASSICURAZIONE
					)
				)
			) DESC
		) = 1
	) s
	ON t.ID_PAZIENTE = s.ID_PAZIENTE
	WHEN MATCHED THEN UPDATE SET
		CODICE_FISCALE = s.CODICE_FISCALE,
		NOME = s.NOME,
		COGNOME = s.COGNOME,
		SESSO = s.SESSO,
		DATA_NASCITA = s.DATA_NASCITA,
		STATO_CIVILE = s.STATO_CIVILE,
		LINGUA_PRIMARIA = s.LINGUA_PRIMARIA,
		GRUPPO_SANGUIGNO = s.GRUPPO_SANGUIGNO,
		CITTA = s.CITTA,
		INDIRIZZO = s.INDIRIZZO,
		CAP = s.CAP,
		PAESE = s.PAESE,
		EMAIL = s.EMAIL,
		TELEFONO = s.TELEFONO,
		COMPAGNIA_ASSICURATIVA = s.COMPAGNIA_ASSICURATIVA,
		PIANO_ASSICURATIVO = s.PIANO_ASSICURATIVO,
		ID_ASSICURAZIONE = s.ID_ASSICURAZIONE,
		CONTATTO_EMERGENZA_NOME = s.CONTATTO_EMERGENZA_NOME,
		CONTATTO_EMERGENZA_TELEFONO = s.CONTATTO_EMERGENZA_TELEFONO,
		ALTEZZA_CM = s.ALTEZZA_CM,
		PESO_KG = s.PESO_KG
	WHEN NOT MATCHED THEN INSERT (
		ID_PAZIENTE,
		CODICE_FISCALE,
		NOME,
		COGNOME,
		SESSO,
		DATA_NASCITA,
		STATO_CIVILE,
		LINGUA_PRIMARIA,
		GRUPPO_SANGUIGNO,
		CITTA,
		INDIRIZZO,
		CAP,
		PAESE,
		EMAIL,
		TELEFONO,
		COMPAGNIA_ASSICURATIVA,
		PIANO_ASSICURATIVO,
		ID_ASSICURAZIONE,
		CONTATTO_EMERGENZA_NOME,
		CONTATTO_EMERGENZA_TELEFONO,
		ALTEZZA_CM,
		PESO_KG
	)
	VALUES (
		s.ID_PAZIENTE,
		s.CODICE_FISCALE,
		s.NOME,
		s.COGNOME,
		s.SESSO,
		s.DATA_NASCITA,
		s.STATO_CIVILE,
		s.LINGUA_PRIMARIA,
		s.GRUPPO_SANGUIGNO,
		s.CITTA,
		s.INDIRIZZO,
		s.CAP,
		s.PAESE,
		s.EMAIL,
		s.TELEFONO,
		s.COMPAGNIA_ASSICURATIVA,
		s.PIANO_ASSICURATIVO,
		s.ID_ASSICURAZIONE,
		s.CONTATTO_EMERGENZA_NOME,
		s.CONTATTO_EMERGENZA_TELEFONO,
		s.ALTEZZA_CM,
		s.PESO_KG
	);

	-- c) MERGE CURATED.REPARTI (dedup deterministica su ID_REPARTO)
	MERGE INTO HEALTHCARE_DW.CURATED.REPARTI t
	USING (
		SELECT
			r.ID_REPARTO,
			r.NOME_REPARTO,
			r.SPECIALITA
		FROM HEALTHCARE_DW.RAW.REPARTI r
		WHERE r.ID_REPARTO IS NOT NULL
		QUALIFY ROW_NUMBER() OVER (
			PARTITION BY r.ID_REPARTO
			ORDER BY MD5(
				TO_VARCHAR(
					OBJECT_CONSTRUCT_KEEP_NULL(
						'NOME_REPARTO', r.NOME_REPARTO,
						'SPECIALITA', r.SPECIALITA
					)
				)
			) DESC
		) = 1
	) s
	ON t.ID_REPARTO = s.ID_REPARTO
	WHEN MATCHED THEN UPDATE SET
		NOME_REPARTO = s.NOME_REPARTO,
		SPECIALITA = s.SPECIALITA
	WHEN NOT MATCHED THEN INSERT (ID_REPARTO, NOME_REPARTO, SPECIALITA)
	VALUES (s.ID_REPARTO, s.NOME_REPARTO, s.SPECIALITA);

	-- d) Quarantena RICOVERI: PK/FK NULL e/o orfani (LEFT JOIN verso CURATED)
	-- MUST-FIX: quarantena deduplicata e deterministica (business key + fallback key su PK NULL)
	INSERT INTO HEALTHCARE_DW.CURATED.RICOVERI_QUARANTENA
	SELECT q.* EXCLUDE (QUARANTINE_KEY, ROW_FINGERPRINT)
	FROM (
		SELECT
			r.*,
			COALESCE(
				TO_VARCHAR(r.ID_RICOVERO),
				MD5(
					TO_VARCHAR(
						OBJECT_CONSTRUCT_KEEP_NULL(
							'ID_RICOVERO', r.ID_RICOVERO,
							'ID_PAZIENTE', r.ID_PAZIENTE,
							'ID_REPARTO', r.ID_REPARTO,
							'DATA_RICOVERO', r.DATA_RICOVERO,
							'DATA_DIMISSIONE', r.DATA_DIMISSIONE,
							'DURATA_DEGENZA_GIORNI', r.DURATA_DEGENZA_GIORNI,
							'TIPO_RICOVERO', r.TIPO_RICOVERO,
							'PROVENIENZA_RICOVERO', r.PROVENIENZA_RICOVERO,
							'ESITO_DIMISSIONE', r.ESITO_DIMISSIONE
						)
					)
				)
			) AS QUARANTINE_KEY,
			MD5(
				TO_VARCHAR(
					OBJECT_CONSTRUCT_KEEP_NULL(
						'ID_PAZIENTE', r.ID_PAZIENTE,
						'ID_REPARTO', r.ID_REPARTO,
						'DATA_RICOVERO', r.DATA_RICOVERO,
						'DATA_DIMISSIONE', r.DATA_DIMISSIONE,
						'DURATA_DEGENZA_GIORNI', r.DURATA_DEGENZA_GIORNI,
						'TIPO_RICOVERO', r.TIPO_RICOVERO,
						'PROVENIENZA_RICOVERO', r.PROVENIENZA_RICOVERO,
						'ESITO_DIMISSIONE', r.ESITO_DIMISSIONE
					)
				)
			) AS ROW_FINGERPRINT
		FROM HEALTHCARE_DW.RAW.RICOVERI r
		LEFT JOIN HEALTHCARE_DW.CURATED.PAZIENTI p
			ON r.ID_PAZIENTE = p.ID_PAZIENTE
		LEFT JOIN HEALTHCARE_DW.CURATED.REPARTI rep
			ON r.ID_REPARTO = rep.ID_REPARTO
		WHERE r.ID_RICOVERO IS NULL
			OR r.ID_PAZIENTE IS NULL
			OR r.ID_REPARTO IS NULL
			OR p.ID_PAZIENTE IS NULL
			OR rep.ID_REPARTO IS NULL
	) q
	QUALIFY ROW_NUMBER() OVER (
		PARTITION BY q.QUARANTINE_KEY
		-- MUST-FIX: fallback timestamp coerente, deterministico e robusto
		ORDER BY COALESCE(
			TRY_TO_TIMESTAMP_NTZ(TO_VARCHAR(q.DATA_RICOVERO)),
			TO_TIMESTAMP_NTZ('1900-01-01 00:00:00')
		) DESC,
		q.ROW_FINGERPRINT DESC
	) = 1;

	-- e) MERGE CURATED.RICOVERI (join valido verso CURATED.PAZIENTI + CURATED.REPARTI)
	MERGE INTO HEALTHCARE_DW.CURATED.RICOVERI t
	USING (
		SELECT
			r.ID_RICOVERO,
			r.ID_PAZIENTE,
			r.ID_REPARTO,
			r.DATA_RICOVERO,
			r.DATA_DIMISSIONE,
			r.DURATA_DEGENZA_GIORNI,
			r.TIPO_RICOVERO,
			r.PROVENIENZA_RICOVERO,
			r.ESITO_DIMISSIONE
		FROM HEALTHCARE_DW.RAW.RICOVERI r
		JOIN HEALTHCARE_DW.CURATED.PAZIENTI p
			ON r.ID_PAZIENTE = p.ID_PAZIENTE
		JOIN HEALTHCARE_DW.CURATED.REPARTI rep
			ON r.ID_REPARTO = rep.ID_REPARTO
		WHERE r.ID_RICOVERO IS NOT NULL
			AND r.ID_PAZIENTE IS NOT NULL
			AND r.ID_REPARTO IS NOT NULL
		QUALIFY ROW_NUMBER() OVER (
			PARTITION BY r.ID_RICOVERO
			ORDER BY r.DATA_RICOVERO DESC,
				MD5(
					TO_VARCHAR(
						OBJECT_CONSTRUCT_KEEP_NULL(
							'ID_PAZIENTE', r.ID_PAZIENTE,
							'ID_REPARTO', r.ID_REPARTO,
							'DATA_RICOVERO', r.DATA_RICOVERO,
							'DATA_DIMISSIONE', r.DATA_DIMISSIONE,
							'DURATA_DEGENZA_GIORNI', r.DURATA_DEGENZA_GIORNI,
							'TIPO_RICOVERO', r.TIPO_RICOVERO,
							'PROVENIENZA_RICOVERO', r.PROVENIENZA_RICOVERO,
							'ESITO_DIMISSIONE', r.ESITO_DIMISSIONE
						)
					)
				) DESC
		) = 1
	) s
	ON t.ID_RICOVERO = s.ID_RICOVERO
	WHEN MATCHED THEN UPDATE SET
		ID_PAZIENTE = s.ID_PAZIENTE,
		ID_REPARTO = s.ID_REPARTO,
		DATA_RICOVERO = s.DATA_RICOVERO,
		DATA_DIMISSIONE = s.DATA_DIMISSIONE,
		DURATA_DEGENZA_GIORNI = s.DURATA_DEGENZA_GIORNI,
		TIPO_RICOVERO = s.TIPO_RICOVERO,
		PROVENIENZA_RICOVERO = s.PROVENIENZA_RICOVERO,
		ESITO_DIMISSIONE = s.ESITO_DIMISSIONE
	WHEN NOT MATCHED THEN INSERT (
		ID_RICOVERO,
		ID_PAZIENTE,
		ID_REPARTO,
		DATA_RICOVERO,
		DATA_DIMISSIONE,
		DURATA_DEGENZA_GIORNI,
		TIPO_RICOVERO,
		PROVENIENZA_RICOVERO,
		ESITO_DIMISSIONE
	)
	VALUES (
		s.ID_RICOVERO,
		s.ID_PAZIENTE,
		s.ID_REPARTO,
		s.DATA_RICOVERO,
		s.DATA_DIMISSIONE,
		s.DURATA_DEGENZA_GIORNI,
		s.TIPO_RICOVERO,
		s.PROVENIENZA_RICOVERO,
		s.ESITO_DIMISSIONE
	);

	-- f) Quarantena PARAMETRI_VITALI: PK/FK NULL e/o orfani (LEFT JOIN verso CURATED.PAZIENTI e RAW.DISPOSITIVI)
	-- MUST-FIX: quarantena deduplicata e deterministica (business key + fallback key su PK NULL)
	INSERT INTO HEALTHCARE_DW.CURATED.PARAMETRI_VITALI_QUARANTENA
	SELECT q.* EXCLUDE (QUARANTINE_KEY, ROW_FINGERPRINT)
	FROM (
		SELECT
			v.*,
			COALESCE(
				TO_VARCHAR(v.ID_MISURAZIONE),
				MD5(
					TO_VARCHAR(
						OBJECT_CONSTRUCT_KEEP_NULL(
							'ID_MISURAZIONE', v.ID_MISURAZIONE,
							'ID_PAZIENTE', v.ID_PAZIENTE,
							'ID_DISPOSITIVO', v.ID_DISPOSITIVO,
							'DATA_MISURAZIONE', v.DATA_MISURAZIONE,
							'FREQUENZA_CARDIACA', v.FREQUENZA_CARDIACA,
							'SATURAZIONE_OSSIGENO', v.SATURAZIONE_OSSIGENO,
							'PRESSIONE_SISTOLICA', v.PRESSIONE_SISTOLICA,
							'PRESSIONE_DIASTOLICA', v.PRESSIONE_DIASTOLICA,
							'TEMPERATURA_C', v.TEMPERATURA_C,
							'FREQUENZA_RESPIRATORIA', v.FREQUENZA_RESPIRATORIA,
							'GLICEMIA_MG_DL', v.GLICEMIA_MG_DL
						)
					)
				)
			) AS QUARANTINE_KEY,
			MD5(
				TO_VARCHAR(
					OBJECT_CONSTRUCT_KEEP_NULL(
						'ID_PAZIENTE', v.ID_PAZIENTE,
						'ID_DISPOSITIVO', v.ID_DISPOSITIVO,
						'DATA_MISURAZIONE', v.DATA_MISURAZIONE,
						'FREQUENZA_CARDIACA', v.FREQUENZA_CARDIACA,
						'SATURAZIONE_OSSIGENO', v.SATURAZIONE_OSSIGENO,
						'PRESSIONE_SISTOLICA', v.PRESSIONE_SISTOLICA,
						'PRESSIONE_DIASTOLICA', v.PRESSIONE_DIASTOLICA,
						'TEMPERATURA_C', v.TEMPERATURA_C,
						'FREQUENZA_RESPIRATORIA', v.FREQUENZA_RESPIRATORIA,
						'GLICEMIA_MG_DL', v.GLICEMIA_MG_DL
					)
				)
			) AS ROW_FINGERPRINT
		FROM HEALTHCARE_DW.RAW.PARAMETRI_VITALI v
		LEFT JOIN HEALTHCARE_DW.CURATED.PAZIENTI p
			ON v.ID_PAZIENTE = p.ID_PAZIENTE
		LEFT JOIN HEALTHCARE_DW.RAW.DISPOSITIVI d
			ON v.ID_DISPOSITIVO = d.ID_DISPOSITIVO
		WHERE v.ID_MISURAZIONE IS NULL
			OR v.ID_PAZIENTE IS NULL
			OR v.ID_DISPOSITIVO IS NULL
			OR p.ID_PAZIENTE IS NULL
			OR d.ID_DISPOSITIVO IS NULL
	) q
	QUALIFY ROW_NUMBER() OVER (
		PARTITION BY q.QUARANTINE_KEY
		-- MUST-FIX: fallback timestamp coerente, deterministico e robusto
		ORDER BY COALESCE(
			TRY_TO_TIMESTAMP_NTZ(TO_VARCHAR(q.DATA_MISURAZIONE)),
			TO_TIMESTAMP_NTZ('1900-01-01 00:00:00')
		) DESC,
		q.ROW_FINGERPRINT DESC
	) = 1;

	-- g) MERGE CURATED.PARAMETRI_VITALI (join valido verso CURATED.PAZIENTI + RAW.DISPOSITIVI)
	MERGE INTO HEALTHCARE_DW.CURATED.PARAMETRI_VITALI t
	USING (
		SELECT
			v.ID_MISURAZIONE,
			v.ID_PAZIENTE,
			v.ID_DISPOSITIVO,
			v.DATA_MISURAZIONE,
			v.FREQUENZA_CARDIACA,
			v.SATURAZIONE_OSSIGENO,
			v.PRESSIONE_SISTOLICA,
			v.PRESSIONE_DIASTOLICA,
			v.TEMPERATURA_C,
			v.FREQUENZA_RESPIRATORIA,
			v.GLICEMIA_MG_DL
		FROM HEALTHCARE_DW.RAW.PARAMETRI_VITALI v
		JOIN HEALTHCARE_DW.CURATED.PAZIENTI p
			ON v.ID_PAZIENTE = p.ID_PAZIENTE
		JOIN HEALTHCARE_DW.RAW.DISPOSITIVI d
			ON v.ID_DISPOSITIVO = d.ID_DISPOSITIVO
		WHERE v.ID_MISURAZIONE IS NOT NULL
			AND v.ID_PAZIENTE IS NOT NULL
			AND v.ID_DISPOSITIVO IS NOT NULL
		QUALIFY ROW_NUMBER() OVER (
			PARTITION BY v.ID_MISURAZIONE
			ORDER BY v.DATA_MISURAZIONE DESC,
				MD5(
					TO_VARCHAR(
						OBJECT_CONSTRUCT_KEEP_NULL(
							'ID_PAZIENTE', v.ID_PAZIENTE,
							'ID_DISPOSITIVO', v.ID_DISPOSITIVO,
							'DATA_MISURAZIONE', v.DATA_MISURAZIONE,
							'FREQUENZA_CARDIACA', v.FREQUENZA_CARDIACA,
							'SATURAZIONE_OSSIGENO', v.SATURAZIONE_OSSIGENO,
							'PRESSIONE_SISTOLICA', v.PRESSIONE_SISTOLICA,
							'PRESSIONE_DIASTOLICA', v.PRESSIONE_DIASTOLICA,
							'TEMPERATURA_C', v.TEMPERATURA_C,
							'FREQUENZA_RESPIRATORIA', v.FREQUENZA_RESPIRATORIA,
							'GLICEMIA_MG_DL', v.GLICEMIA_MG_DL
						)
					)
				) DESC
		) = 1
	) s
	ON t.ID_MISURAZIONE = s.ID_MISURAZIONE
	WHEN MATCHED THEN UPDATE SET
		ID_PAZIENTE = s.ID_PAZIENTE,
		ID_DISPOSITIVO = s.ID_DISPOSITIVO,
		DATA_MISURAZIONE = s.DATA_MISURAZIONE,
		FREQUENZA_CARDIACA = s.FREQUENZA_CARDIACA,
		SATURAZIONE_OSSIGENO = s.SATURAZIONE_OSSIGENO,
		PRESSIONE_SISTOLICA = s.PRESSIONE_SISTOLICA,
		PRESSIONE_DIASTOLICA = s.PRESSIONE_DIASTOLICA,
		TEMPERATURA_C = s.TEMPERATURA_C,
		FREQUENZA_RESPIRATORIA = s.FREQUENZA_RESPIRATORIA,
		GLICEMIA_MG_DL = s.GLICEMIA_MG_DL
	WHEN NOT MATCHED THEN INSERT (
		ID_MISURAZIONE,
		ID_PAZIENTE,
		ID_DISPOSITIVO,
		DATA_MISURAZIONE,
		FREQUENZA_CARDIACA,
		SATURAZIONE_OSSIGENO,
		PRESSIONE_SISTOLICA,
		PRESSIONE_DIASTOLICA,
		TEMPERATURA_C,
		FREQUENZA_RESPIRATORIA,
		GLICEMIA_MG_DL
	)
	VALUES (
		s.ID_MISURAZIONE,
		s.ID_PAZIENTE,
		s.ID_DISPOSITIVO,
		s.DATA_MISURAZIONE,
		s.FREQUENZA_CARDIACA,
		s.SATURAZIONE_OSSIGENO,
		s.PRESSIONE_SISTOLICA,
		s.PRESSIONE_DIASTOLICA,
		s.TEMPERATURA_C,
		s.FREQUENZA_RESPIRATORIA,
		s.GLICEMIA_MG_DL
	);

	RETURN 'OK';
END;
$$;
```

=== 3) ANALYTICS: sp_publish_analytics() (solo MERGE, idempotente)

La procedura esegue esclusivamente `MERGE` idempotenti sulle business key, senza DDL e senza `INSERT` di popolamento.

```sql
USE ROLE ROLE_DATA_ENGINEER;
USE DATABASE HEALTHCARE_DW;
USE SCHEMA HEALTHCARE_DW.PIPELINE;

CREATE OR REPLACE PROCEDURE sp_publish_analytics()
	RETURNS STRING
	LANGUAGE SQL
	EXECUTE AS OWNER
AS
$$
BEGIN
	-- a) DIM
	MERGE INTO HEALTHCARE_DW.ANALYTICS.DIM_PAZIENTE t
	USING (
		SELECT
			ID_PAZIENTE,
			SESSO,
			DATA_NASCITA,
			CITTA,
			GRUPPO_SANGUIGNO,
			PIANO_ASSICURATIVO
		FROM HEALTHCARE_DW.CURATED.PAZIENTI
	) s
	ON t.ID_PAZIENTE = s.ID_PAZIENTE
	WHEN MATCHED THEN UPDATE SET
		SESSO = s.SESSO,
		DATA_NASCITA = s.DATA_NASCITA,
		CITTA = s.CITTA,
		GRUPPO_SANGUIGNO = s.GRUPPO_SANGUIGNO,
		PIANO_ASSICURATIVO = s.PIANO_ASSICURATIVO
	WHEN NOT MATCHED THEN INSERT (ID_PAZIENTE, SESSO, DATA_NASCITA, CITTA, GRUPPO_SANGUIGNO, PIANO_ASSICURATIVO)
	VALUES (s.ID_PAZIENTE, s.SESSO, s.DATA_NASCITA, s.CITTA, s.GRUPPO_SANGUIGNO, s.PIANO_ASSICURATIVO);

	MERGE INTO HEALTHCARE_DW.ANALYTICS.DIM_REPARTO t
	USING (
		SELECT
			ID_REPARTO,
			NOME_REPARTO,
			SPECIALITA
		FROM HEALTHCARE_DW.CURATED.REPARTI
	) s
	ON t.ID_REPARTO = s.ID_REPARTO
	WHEN MATCHED THEN UPDATE SET
		NOME_REPARTO = s.NOME_REPARTO,
		SPECIALITA = s.SPECIALITA
	WHEN NOT MATCHED THEN INSERT (ID_REPARTO, NOME_REPARTO, SPECIALITA)
	VALUES (s.ID_REPARTO, s.NOME_REPARTO, s.SPECIALITA);

	-- b) FACT_RICOVERI
	MERGE INTO HEALTHCARE_DW.ANALYTICS.FACT_RICOVERI t
	USING (
		SELECT
			ID_RICOVERO,
			ID_PAZIENTE,
			ID_REPARTO,
			DATA_RICOVERO AS TS_RICOVERO,
			DATA_DIMISSIONE AS TS_DIMISSIONE,
			DURATA_DEGENZA_GIORNI,
			TIPO_RICOVERO,
			ESITO_DIMISSIONE
		FROM HEALTHCARE_DW.CURATED.RICOVERI
	) s
	ON t.ID_RICOVERO = s.ID_RICOVERO
	WHEN MATCHED THEN UPDATE SET
		ID_PAZIENTE = s.ID_PAZIENTE,
		ID_REPARTO = s.ID_REPARTO,
		TS_RICOVERO = s.TS_RICOVERO,
		TS_DIMISSIONE = s.TS_DIMISSIONE,
		DURATA_DEGENZA_GIORNI = s.DURATA_DEGENZA_GIORNI,
		TIPO_RICOVERO = s.TIPO_RICOVERO,
		ESITO_DIMISSIONE = s.ESITO_DIMISSIONE
	WHEN NOT MATCHED THEN INSERT (
		ID_RICOVERO,
		ID_PAZIENTE,
		ID_REPARTO,
		TS_RICOVERO,
		TS_DIMISSIONE,
		DURATA_DEGENZA_GIORNI,
		TIPO_RICOVERO,
		ESITO_DIMISSIONE
	)
	VALUES (
		s.ID_RICOVERO,
		s.ID_PAZIENTE,
		s.ID_REPARTO,
		s.TS_RICOVERO,
		s.TS_DIMISSIONE,
		s.DURATA_DEGENZA_GIORNI,
		s.TIPO_RICOVERO,
		s.ESITO_DIMISSIONE
	);

	-- c) FACT_MISURAZIONI (ORA_GIORNO derivata)
	MERGE INTO HEALTHCARE_DW.ANALYTICS.FACT_MISURAZIONI t
	USING (
		SELECT
			ID_MISURAZIONE,
			ID_PAZIENTE,
			ID_DISPOSITIVO,
			DATA_MISURAZIONE AS TS_MISURAZIONE,
			EXTRACT(HOUR FROM DATA_MISURAZIONE) AS ORA_GIORNO,
			FREQUENZA_CARDIACA,
			SATURAZIONE_OSSIGENO,
			PRESSIONE_SISTOLICA,
			PRESSIONE_DIASTOLICA,
			TEMPERATURA_C,
			GLICEMIA_MG_DL
		FROM HEALTHCARE_DW.CURATED.PARAMETRI_VITALI
	) s
	ON t.ID_MISURAZIONE = s.ID_MISURAZIONE
	WHEN MATCHED THEN UPDATE SET
		ID_PAZIENTE = s.ID_PAZIENTE,
		ID_DISPOSITIVO = s.ID_DISPOSITIVO,
		TS_MISURAZIONE = s.TS_MISURAZIONE,
		ORA_GIORNO = s.ORA_GIORNO,
		FREQUENZA_CARDIACA = s.FREQUENZA_CARDIACA,
		SATURAZIONE_OSSIGENO = s.SATURAZIONE_OSSIGENO,
		PRESSIONE_SISTOLICA = s.PRESSIONE_SISTOLICA,
		PRESSIONE_DIASTOLICA = s.PRESSIONE_DIASTOLICA,
		TEMPERATURA_C = s.TEMPERATURA_C,
		GLICEMIA_MG_DL = s.GLICEMIA_MG_DL
	WHEN NOT MATCHED THEN INSERT (
		ID_MISURAZIONE,
		ID_PAZIENTE,
		ID_DISPOSITIVO,
		TS_MISURAZIONE,
		ORA_GIORNO,
		FREQUENZA_CARDIACA,
		SATURAZIONE_OSSIGENO,
		PRESSIONE_SISTOLICA,
		PRESSIONE_DIASTOLICA,
		TEMPERATURA_C,
		GLICEMIA_MG_DL
	)
	VALUES (
		s.ID_MISURAZIONE,
		s.ID_PAZIENTE,
		s.ID_DISPOSITIVO,
		s.TS_MISURAZIONE,
		s.ORA_GIORNO,
		s.FREQUENZA_CARDIACA,
		s.SATURAZIONE_OSSIGENO,
		s.PRESSIONE_SISTOLICA,
		s.PRESSIONE_DIASTOLICA,
		s.TEMPERATURA_C,
		s.GLICEMIA_MG_DL
	);

	RETURN 'OK';
END;
$$;
```

== Orchestrazione e scheduling (HEALTHCARE_DW.PIPELINE)

L'orchestrazione è implementata con *TASK* in catena (`AFTER`) nello schema tecnico `HEALTHCARE_DW.PIPELINE`, con scheduling giornaliero alle 02:00 (Europe/Rome) sul task root.

=== Grant strutturali (staging + schema)

```sql
USE ROLE SECURITYADMIN;

-- Staging (RAW)
GRANT USAGE ON FILE FORMAT HEALTHCARE_DW.RAW.ff_parquet TO ROLE ROLE_DATA_ENGINEER;
GRANT USAGE ON STAGE HEALTHCARE_DW.RAW.stage_healthcare_raw TO ROLE ROLE_DATA_ENGINEER;

```

*Task chain: procedure → task root schedulato → task downstream*

Le procedure sono richiamate dai task e sono definite con `EXECUTE AS OWNER`.
La sequenza di creazione è: procedure → task chain → grant runtime.

```sql
USE ROLE ROLE_DATA_ENGINEER;
USE DATABASE HEALTHCARE_DW;
USE SCHEMA HEALTHCARE_DW.PIPELINE;

CREATE OR REPLACE TASK task_load_raw
	WAREHOUSE = WH_INGEST
	SCHEDULE = 'USING CRON 0 2 * * * Europe/Rome'
AS
	CALL HEALTHCARE_DW.PIPELINE.sp_load_raw();

CREATE OR REPLACE TASK task_transform_curated
	WAREHOUSE = WH_OPERATIONS
	AFTER task_load_raw
AS
	CALL HEALTHCARE_DW.PIPELINE.sp_transform_curated();

CREATE OR REPLACE TASK task_publish_analytics
	WAREHOUSE = WH_ANALYTICS
	AFTER task_transform_curated
AS
	CALL HEALTHCARE_DW.PIPELINE.sp_publish_analytics();
```

=== Grant runtime (warehouse + execute + operate)

Questi grant rendono eseguibile la pipeline con `ROLE_DATA_ENGINEER` (warehouse, database/schema e controllo operativo dei task tramite `OPERATE`).
Il privilegio `OPERATE` governa l'operatività (resume/suspend/execute/monitor) senza concedere privilegi amministrativi più ampi.

```sql
USE ROLE SECURITYADMIN;

-- Warehouse
GRANT USAGE ON WAREHOUSE WH_INGEST TO ROLE ROLE_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE WH_OPERATIONS TO ROLE ROLE_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE WH_ANALYTICS TO ROLE ROLE_DATA_ENGINEER;

-- Stored Procedures (USAGE, non EXECUTE)
GRANT USAGE ON PROCEDURE HEALTHCARE_DW.PIPELINE.sp_load_raw()
    TO ROLE ROLE_DATA_ENGINEER;

GRANT USAGE ON PROCEDURE HEALTHCARE_DW.PIPELINE.sp_transform_curated()
    TO ROLE ROLE_DATA_ENGINEER;

GRANT USAGE ON PROCEDURE HEALTHCARE_DW.PIPELINE.sp_publish_analytics()
    TO ROLE ROLE_DATA_ENGINEER;

-- Task
GRANT OPERATE ON TASK HEALTHCARE_DW.PIPELINE.task_load_raw
    TO ROLE ROLE_DATA_ENGINEER;

GRANT OPERATE ON TASK HEALTHCARE_DW.PIPELINE.task_transform_curated
    TO ROLE ROLE_DATA_ENGINEER;

GRANT OPERATE ON TASK HEALTHCARE_DW.PIPELINE.task_publish_analytics
    TO ROLE ROLE_DATA_ENGINEER;

GRANT EXECUTE TASK ON ACCOUNT TO ROLE ROLE_DATA_ENGINEER;
```

=== Ownership e delega operativa (EXECUTE AS OWNER)

- Le procedure e i task vengono creati con `ROLE_DATA_ENGINEER` (owner degli oggetti in `HEALTHCARE_DW.PIPELINE`).
- `EXECUTE AS OWNER` implica che l'esecuzione delle procedure usa i privilegi dell'owner della procedura.
- Il controllo operativo della catena (resume/suspend/execute/monitor) viene delegato esplicitamente via `GRANT OPERATE` sui task.

*Attivazione della catena e run end-to-end controllato (evidenza)*

```sql
USE ROLE ROLE_DATA_ENGINEER;
ALTER TASK HEALTHCARE_DW.PIPELINE.task_load_raw SUSPEND;
ALTER TASK HEALTHCARE_DW.PIPELINE.task_transform_curated RESUME;
ALTER TASK HEALTHCARE_DW.PIPELINE.task_publish_analytics RESUME;

EXECUTE TASK HEALTHCARE_DW.PIPELINE.task_load_raw;
```

*Verifica esecuzione*

Per confermare il corretto funzionamento della pipeline, interrogo lo storico dei task per verificare che tutti i task della catena siano in stato `SUCCEEDED`.

#figure(
  ```sql
  SELECT 
      NAME, 
      STATE, 
      ERROR_MESSAGE, 
      SCHEDULED_TIME, 
      COMPLETED_TIME, 
      TIMESTAMPDIFF('second', SCHEDULED_TIME, COMPLETED_TIME) as DURATION_SEC
  FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
      SCHEDULED_TIME_RANGE_START => DATEADD('minute', -4, CURRENT_TIMESTAMP())
  ))
  WHERE DATABASE_NAME = 'HEALTHCARE_DW'
  AND NAME IN ('TASK_LOAD_RAW','TASK_TRANSFORM_CURATED','TASK_PUBLISH_ANALYTICS')
  ORDER BY SCHEDULED_TIME DESC;
  ```,
  caption: "Query di verifica: stato di esecuzione della catena di task"
)

// Screenshot suggerito: sf_task_history_success_chain.png
#figure(
  image("../assets/sf_task_history_success_chain.png", width: 90%),
  caption: "Screenshot: evidenza dell'esecuzione a cascata (Load -> Transform -> Publish) completata con successo"
)
